#!/bin/sh
set -u
set -e

# set up EPEL, install python-qpid-proton
# working around some limitations in Dogen's repos plugin

SCRIPT_DIR=$(dirname $0)
mv $SCRIPT_DIR/epel.repo /etc/yum.repos.d
rpm --import $SCRIPT_DIR/RPM-GPG-KEY-EPEL-7
yum install -y python-qpid-proton
yum clean all
rm /etc/yum.repos.d/epel.repo
