FROM rhel7

RUN yum -y install \
    gettext \
    hostname \
    iputils \
    && yum clean all

ADD qpid-dispatch-binary.tar.gz /
COPY ./run_qdr.sh ./qdrouterd.conf.template colocated-topic.snippet ssl.snippet subscriptions.snippet amqp-kafka-bridge.snippet /etc/qpid-dispatch/

EXPOSE 5672 55672 5671
CMD ["/etc/qpid-dispatch/run_qdr.sh"]
