#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)

DISTRO_NAME=topic-forwarder

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv "$DISTRO_NAME" /opt
#    ln -s "/opt/$DISTRO_NAME" "/opt/topic-forwarder"
}
chown -R jboss:jboss /opt/topic-forwarder
chmod -R a+rwX $HOME
chmod -R a+rwX /opt/topic-forwarder