#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

mkdir --parents /opt/mqtt-lwt

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tar.gz"
    mv mqtt-lwt.jar /opt/mqtt-lwt/
}

mv $ADDED_DIR/run_mqtt.sh /opt/mqtt-lwt
chmod +x /opt/mqtt-lwt/run_mqtt.sh
