#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)

DISTRO_NAME=server

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv "$DISTRO_NAME" /opt
}

#need to create home dir for community images
mkdir -p /home/jboss
chown 185 /home/jboss
chmod -R a+rwx /home/jboss
