#!/bin/sh

set -e

DISTRO_NAME=configserv

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv "$DISTRO_NAME" /opt
}
#need to create home dir for community images
mkdir -p /home/jboss
chown 185 /home/jboss
chmod -R a+rwX /home/jboss
